import React from "react";
import { FC } from "react";
import Head from "next/head";
import { Box, Center, Text } from "@chakra-ui/react";
import Section from "../Section";
import CreateSection from "../CreateSection";
import axios from "axios";
import MainLayout from "../layout/MainLayout";
import { GetStaticProps } from "next";
import { ISection, ISectionData } from "@/interfaces/ISection";
import { NextPage } from "next";

const Home: FC<ISectionData> = ({ sections }) => {
  return (
    <MainLayout words={sections.length}>
      <Head>
        <title>Home Page | Your Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={"flex"} flexWrap={"wrap"}>
        <>
          {sections.map(({ id, category, word, translate, sentence }, index) => (
            <Section
              key={index}
              id={id}
              category={category}
              word={word}
              translate={translate}
              sentence={sentence}
            />
          ))}
          <Box p={"25px"}>
            <CreateSection />
          </Box>
        </>
      </Box>
    </MainLayout>
  );
};

export default Home;
