import GetStarted from "@/components/screens/GetStarted";
import GetStarted2 from "@/components/screens/GetStarted2";
import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function getStartedPage() {
  return (
    <>
      <Head>
        <title>Get Started | Your Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GetStarted2 />
    </>
  );
}
